# Generated by Django 3.2.9 on 2021-11-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactClass',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='', max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('query_subject', models.CharField(default='', max_length=10)),
                ('query_desc', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
