# Generated by Django 3.2.9 on 2021-12-08 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import make_blog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(default='', max_length=512)),
                ('blog_url', models.SlugField(blank=True, default='', help_text='Leave blank if you donot want custom url', max_length=512, unique=True)),
                ('blog_image', models.ImageField(blank=True, default='', null=True, upload_to='blog/image/%Y/%m/%d')),
                ('blog_status', models.CharField(choices=[('d', 'draft'), ('p', 'published'), ('w', 'withdrawn')], default='d', max_length=1)),
                ('blog_date', models.DateTimeField()),
                ('blog_content', models.TextField()),
                ('blog_author', models.ForeignKey(editable=False, on_delete=models.SET(make_blog.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=255, unique=True)),
                ('category_url', models.SlugField(max_length=255, unique=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactClass',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='', max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('query_subject', models.CharField(default='', max_length=225)),
                ('query_desc', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='blog/%Y/%m/%d/image')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_image', models.ImageField(blank=True, default='', null=True, upload_to='user/images/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=models.SET(make_blog.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='make_blog.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='make_blog.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_category',
            field=models.ForeignKey(on_delete=models.SET(make_blog.models.get_sentinel_category), to='make_blog.blogcategory'),
        ),
    ]
