# Generated by Django 3.2.9 on 2021-12-18 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='', max_length=50, unique=True)),
                ('plan_price', models.PositiveIntegerField(default=0, unique=True)),
                ('plan_desc', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='make_blog.pricing'),
        ),
    ]
