# Generated by Django 3.2.9 on 2021-12-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default='', upload_to='blog/image/%Y/%m/%d'),
        ),
    ]
