# Generated by Django 3.2.9 on 2022-02-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EditableSetting',
            new_name='Configuration',
        ),
    ]
