# Generated by Django 3.2.9 on 2021-12-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0002_auto_20211219_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='plan_price',
            field=models.PositiveIntegerField(default=0, help_text='All prices in indian rupees', unique=True),
        ),
    ]
