# Generated by Django 3.2.9 on 2021-12-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0002_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactclass',
            name='query_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
