# Generated by Django 3.2.9 on 2022-01-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0002_auto_20220121_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='testimonial',
            field=models.BooleanField(default=False),
        ),
    ]
