# Generated by Django 3.2.9 on 2021-12-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0003_alter_pricing_plan_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('BANKNAME', models.CharField(max_length=20)),
                ('BANKTXNID', models.CharField(max_length=20)),
                ('CURRENCY', models.CharField(max_length=4)),
                ('GATEWAYNAME', models.CharField(max_length=20)),
                ('ORDERID', models.CharField(max_length=30)),
                ('PAYMENTMODE', models.CharField(max_length=10)),
                ('RESPCODE', models.CharField(max_length=10)),
                ('RESPMSG', models.CharField(max_length=200)),
                ('STATUS', models.CharField(max_length=10)),
                ('TXNAMOUNT', models.CharField(max_length=10)),
                ('TXNDATE', models.DateTimeField()),
                ('TXNID', models.CharField(max_length=30)),
            ],
        ),
    ]
