# Generated by Django 3.2.9 on 2021-12-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0003_contactclass_query_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
