# Generated by Django 3.2.9 on 2022-02-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0004_alter_youtubecourseplaylist_course_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubecourseplaylist',
            name='video_thumbnail_default',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='youtubecourseplaylist',
            name='video_thumbnail_high',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='youtubecourseplaylist',
            name='video_thumbnail_medium',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='youtubecourseplaylist',
            name='video_thumbnail_standard',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
