# Generated by Django 3.2.9 on 2022-01-22 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0004_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_image',
            field=models.FileField(default='', upload_to='feature/image/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])]),
        ),
    ]
