# Generated by Django 3.2.9 on 2022-02-06 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0005_auto_20220206_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
