# Generated by Django 3.2.9 on 2022-01-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0005_alter_feature_feature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
