# Generated by Django 3.2.9 on 2021-12-19 10:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('make_blog', '0005_transctiondetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransctionDetails',
            new_name='TransctionDetail',
        ),
    ]
