# Generated by Django 3.2.9 on 2021-12-19 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0006_rename_transctiondetails_transctiondetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transctiondetail',
            name='status',
            field=models.CharField(choices=[('n', 'Payment Not Done'), ('f', 'Payment Failed'), ('s', 'Success'), ('w', 'Payment withdrawn')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='transctiondetail',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
