# Generated by Django 3.2.9 on 2022-02-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0006_youtubevideo_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='site_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
