# Generated by Django 3.2.9 on 2022-02-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0007_configuration_site_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='typed_strings',
            field=models.TextField(default='hi'),
        ),
    ]
