# Generated by Django 3.2.9 on 2022-02-11 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0008_configuration_typed_strings'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='banner',
            field=models.FileField(blank=True, default='', null=True, upload_to='home/image/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='welcome_image_1',
            field=models.FileField(blank=True, default='', null=True, upload_to='home/image/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='welcome_image_2',
            field=models.FileField(blank=True, default='', null=True, upload_to='home/image/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='welcome_text',
            field=models.CharField(default='Welcome Cool Developer', help_text='Set Up your welcome title', max_length=255),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='typed_strings',
            field=models.TextField(blank=True, default='hi', help_text='Use comma separated Typed JS string values', null=True),
        ),
    ]
