# Generated by Django 3.2.9 on 2022-01-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0008_alter_transctiondetail_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='plan_users',
            field=models.IntegerField(default=0),
        ),
    ]
