# Generated by Django 3.2.9 on 2022-01-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0009_pricing_plan_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='premium_blogs',
            field=models.IntegerField(default=5),
        ),
    ]
