# Generated by Django 3.2.9 on 2022-02-11 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('make_blog', '0009_auto_20220211_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='followers',
            field=models.ManyToManyField(related_name='Follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='welcome_text',
            field=models.CharField(default='Welcome to Cool Developer', help_text='Set Up your welcome title', max_length=255),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
