# Generated by Django 3.2.9 on 2022-01-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0010_pricing_premium_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='premium_blog',
            field=models.IntegerField(default=5),
        ),
    ]
