# Generated by Django 3.2.9 on 2022-01-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0011_auto_20220116_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_premium',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='premium_blogs',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='premium_blog',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='ratings',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='star_ratings',
            field=models.CharField(choices=[(0, 'NO RATING'), (1, '1 STAR'), (2, '2 STAR'), (3, '3 STAR'), (4, '4 STAR'), (5, '4 STAR')], default=0, max_length=1),
        ),
    ]
