# Generated by Django 3.2.9 on 2022-02-12 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0011_configuration_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='apple_touch_icon',
            field=models.FileField(blank=True, default='', help_text='Select a Apple Touch Icon File', null=True, upload_to='icon/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='icon',
            field=models.FileField(blank=True, default='', help_text='Select a .ico Icon File', null=True, upload_to='icon/', validators=[django.core.validators.FileExtensionValidator(['ico'])]),
        ),
    ]
