# Generated by Django 3.2.9 on 2022-02-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0012_auto_20220212_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Enter Your Full Address', null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='contact_number',
            field=models.CharField(blank=True, default='', help_text='Enter your phone number', max_length=16, null=True),
        ),
    ]
