# Generated by Django 3.2.9 on 2022-01-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_blog', '0013_alter_usermodel_star_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='rating_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
